import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./chakra/providers";
import { ColorModeScript } from '@chakra-ui/react'
import { extendTheme } from '@chakra-ui/react'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const config = {
  initialColorMode: 'dark', // 'dark' | 'light'
  useSystemColorMode: false,
}

const theme = extendTheme({ config })

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body id="body" className={inter.className}>
        <Providers>
          <ColorModeScript initialColorMode={theme.config.initialColorMode} />
            {children} 
        </Providers>
      </body>
    </html>
  );
}
